WIP: Project Cleanup Take 2
purinda/docker-compose-ansible-playbook-for-aws-ec2 pull request #7
Opened 2018-07-10 11:24 UTC by purinda

**WIP: Do not review**

### Tasks
- [ ] Remove unwanted ansible configurations
- [ ] Pre tasks required for ubuntu distros (python 2.x setup) should be moved from sample.yml to a proper role.

2018-07-18 04:31 UTC, jordonsc requested changes

2018-07-18 04:31 UTC, jordonsc commented on src/os.sh
> +[ $CLI_OS ] && return || CLI_OS=1
Convention would have this be `$OS_SH`

2018-07-18 04:31 UTC, jordonsc commented on ansible/roles/docker/tasks/main.yml
> +  retries: 10
wtf

2018-07-18 04:35 UTC, purinda commented on ansible/roles/docker/tasks/main.yml
> +  retries: 10
yeah try for around 50secs, until the service becomes active. Feels like a hack looking back, I will try to use `notify` here.

2018-07-18 04:35 UTC, purinda commented on src/os.sh
> +[ $CLI_OS ] && return || CLI_OS=1
is there some doc which you can refer to for this sort of conventions.

2018-07-18 04:35 UTC, purinda commented on src/os.sh
> +[ $CLI_OS ] && return || CLI_OS=1
I will change it.

2018-07-18 04:41 UTC, jordonsc commented on src/os.sh
> +[ $CLI_OS ] && return || CLI_OS=1
the variable name matches the file name

2018-07-18 04:51 UTC, purinda commented on src/os.sh
> +[ $CLI_OS ] && return || CLI_OS=1
make sense, good ol' c style.

2018-07-27 04:23 UTC, purinda commented
@jordonsc I fixed the review comments, have a look thanks. Also tested using Ubuntu AMIs.

2018-07-31 00:28 UTC, jordonsc approved these changes

2018-07-31 02:13 UTC, merged